#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build CTGTRec continuous-time user-item adjacency matrices.

For each dataset, this script reads:

    data/<dataset>/<dataset>_temporal.inter

Only training interactions (``x_label == 0``) are used to construct the graph.
Validation and test interactions are used only to determine the complete user
and item ID ranges; they never contribute graph edges or temporal statistics.

For each training interaction ``(u, i, t_ui)``:

    span_u  = t_last_u - t_first_u
    delta_ui = (t_last_u - t_ui) / max(span_u, epsilon)
    w_ui     = exp(-delta_ui / tau)

The weighted undirected bipartite adjacency matrix is then symmetrically
normalized:

    A_norm = D^(-1/2) A D^(-1/2)

If a user has multiple training interactions with the same item, their temporal
weights are summed into the same user-item matrix entry before normalization.
No static graph, global-time graph, timestamp snapshots, or minimum-weight
clipping is generated by this final CTGTRec preprocessing script.

Example:

    python preprocessing/build_continuous_time_adj.py \
        --data_root data \
        --datasets baby \
        --taus 0.30
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Sequence

import numpy as np
import pandas as pd
import scipy.sparse as sp


REQUIRED_COLUMNS = ["userID", "itemID", "timestamp", "x_label"]
VALID_LABELS = {0, 1, 2}


def safe_float_for_name(value: float) -> str:
    """Convert a positive float to the filename form used by CTGTRec."""
    if not math.isfinite(value) or value <= 0:
        raise ValueError(f"tau must be finite and positive, received {value}.")
    return ("%.12g" % float(value)).replace("-", "m").replace(".", "p")


def normalize_column_names(df: pd.DataFrame, path: Path) -> pd.DataFrame:
    """Support plain MMRec columns and typed names such as userID:token."""
    normalized = [str(column).split(":", 1)[0] for column in df.columns]
    if len(set(normalized)) != len(normalized):
        raise ValueError(
            f"{path}: typed-column normalization creates duplicate names: "
            f"{normalized}."
        )
    result = df.copy()
    result.columns = normalized
    return result


def coerce_nonnegative_integer(
    df: pd.DataFrame,
    column: str,
    path: Path,
) -> None:
    """Validate an integer ID/label column without silently truncating values."""
    numeric = pd.to_numeric(df[column], errors="raise")
    values = numeric.to_numpy(dtype=np.float64)
    if not np.isfinite(values).all():
        raise ValueError(f"{path}: {column} contains non-finite values.")
    if not np.equal(values, np.floor(values)).all():
        raise ValueError(f"{path}: {column} must contain integer values.")
    if (values < 0).any():
        raise ValueError(f"{path}: {column} contains negative values.")
    df[column] = numeric.astype(np.int64)


def read_temporal_inter(path: Path, separator: str) -> pd.DataFrame:
    """Read and validate a temporally labelled MMRec interaction file."""
    if not path.is_file():
        raise FileNotFoundError(f"Temporal interaction file not found: {path}")

    df = pd.read_csv(path, sep=separator)
    df = normalize_column_names(df, path)
    missing = [column for column in REQUIRED_COLUMNS if column not in df.columns]
    if missing:
        raise ValueError(
            f"{path}: missing required columns {missing}; available columns are "
            f"{list(df.columns)}."
        )

    df = df[REQUIRED_COLUMNS].copy()
    if df.empty:
        raise ValueError(f"{path}: interaction file is empty.")
    if df.isna().any().any():
        counts = df.isna().sum()
        counts = counts[counts > 0].to_dict()
        raise ValueError(f"{path}: missing values found: {counts}")

    coerce_nonnegative_integer(df, "userID", path)
    coerce_nonnegative_integer(df, "itemID", path)
    coerce_nonnegative_integer(df, "x_label", path)

    labels = set(df["x_label"].unique().tolist())
    if not labels.issubset(VALID_LABELS):
        raise ValueError(
            f"{path}: unexpected x_label values {sorted(labels)}; expected 0/1/2."
        )
    if labels != VALID_LABELS:
        raise ValueError(
            f"{path}: expected train/valid/test labels 0, 1 and 2, found "
            f"{sorted(labels)}. Run the strict temporal splitter first."
        )

    timestamp = pd.to_numeric(df["timestamp"], errors="raise")
    timestamp_values = timestamp.to_numpy(dtype=np.float64)
    if not np.isfinite(timestamp_values).all():
        raise ValueError(f"{path}: timestamp contains non-finite values.")
    df["timestamp"] = timestamp.astype(np.float64)
    return df


def validate_contiguous_ids(df: pd.DataFrame, path: Path) -> tuple[int, int]:
    """Require the zero-based contiguous IDs expected by MMRec feature arrays."""
    user_ids = np.sort(df["userID"].unique())
    item_ids = np.sort(df["itemID"].unique())
    expected_users = np.arange(int(user_ids[-1]) + 1, dtype=np.int64)
    expected_items = np.arange(int(item_ids[-1]) + 1, dtype=np.int64)

    if not np.array_equal(user_ids, expected_users):
        missing = np.setdiff1d(expected_users, user_ids)[:20].tolist()
        raise ValueError(
            f"{path}: userID is not contiguous from zero. Missing examples: "
            f"{missing}"
        )
    if not np.array_equal(item_ids, expected_items):
        missing = np.setdiff1d(expected_items, item_ids)[:20].tolist()
        raise ValueError(
            f"{path}: itemID is not contiguous from zero. Missing examples: "
            f"{missing}"
        )
    return len(expected_users), len(expected_items)


def validate_side_files(
    dataset_dir: Path,
    *,
    n_users: int,
    n_items: int,
) -> dict[str, Any]:
    """Validate optional mapping/feature row counts instead of ignoring errors."""
    checks: dict[str, Any] = {}

    mapping_specs = [
        ("u_id_mapping.csv", "userID", n_users),
        ("i_id_mapping.csv", "itemID", n_items),
    ]
    for filename, id_column, expected_count in mapping_specs:
        path = dataset_dir / filename
        if not path.exists():
            checks[filename] = "not_present"
            continue
        mapping = pd.read_csv(path, sep="\t")
        if id_column not in mapping.columns:
            raise ValueError(
                f"{path}: expected column {id_column!r}; found "
                f"{list(mapping.columns)}."
            )
        values = pd.to_numeric(mapping[id_column], errors="raise").to_numpy()
        if len(values) != expected_count:
            raise ValueError(
                f"{path}: expected {expected_count} rows, found {len(values)}."
            )
        if not np.array_equal(
            np.sort(values.astype(np.int64)),
            np.arange(expected_count, dtype=np.int64),
        ):
            raise ValueError(f"{path}: {id_column} is not contiguous from zero.")
        checks[filename] = int(len(values))

    for filename in ("image_feat.npy", "text_feat.npy"):
        path = dataset_dir / filename
        if not path.exists():
            checks[filename] = "not_present"
            continue
        array = np.load(path, mmap_mode="r")
        if array.ndim != 2:
            raise ValueError(f"{path}: expected a 2-D feature array, found {array.shape}.")
        if int(array.shape[0]) != n_items:
            raise ValueError(
                f"{path}: expected {n_items} item rows, found {array.shape[0]}."
            )
        checks[filename] = [int(array.shape[0]), int(array.shape[1])]

    return checks


def compute_user_normalized_delta(
    train_df: pd.DataFrame,
    *,
    epsilon: float,
) -> np.ndarray:
    """Compute the paper's train-only user-normalized temporal distance."""
    if not math.isfinite(epsilon) or epsilon <= 0:
        raise ValueError(f"epsilon must be finite and positive, received {epsilon}.")

    grouped = train_df.groupby("userID", sort=False)["timestamp"]
    user_last = grouped.transform("max").to_numpy(dtype=np.float64)
    user_first = grouped.transform("min").to_numpy(dtype=np.float64)
    timestamps = train_df["timestamp"].to_numpy(dtype=np.float64)

    user_span = user_last - user_first
    denominator = np.maximum(user_span, float(epsilon))
    delta = (user_last - timestamps) / denominator

    tolerance = 1e-12
    if (delta < -tolerance).any() or (delta > 1.0 + tolerance).any():
        raise RuntimeError(
            "Computed temporal distances are outside [0, 1]; check timestamps."
        )
    return np.clip(delta, 0.0, 1.0)


def make_temporal_weights(delta: np.ndarray, tau: float) -> np.ndarray:
    """Apply the exponential continuous-time kernel."""
    if not math.isfinite(tau) or tau <= 0:
        raise ValueError(f"tau must be finite and positive, received {tau}.")
    weights = np.exp(-delta / float(tau)).astype(np.float32)
    if not np.isfinite(weights).all() or (weights <= 0).any() or (weights > 1).any():
        raise RuntimeError("Temporal weights must be finite and lie in (0, 1].")
    return weights


def build_raw_bipartite_adjacency(
    users: np.ndarray,
    items: np.ndarray,
    weights: np.ndarray,
    *,
    n_users: int,
    n_items: int,
) -> sp.csr_matrix:
    """Build a symmetric graph and sum duplicate user-item contributions."""
    shifted_items = n_users + items
    rows = np.concatenate([users, shifted_items])
    columns = np.concatenate([shifted_items, users])
    values = np.concatenate([weights, weights]).astype(np.float32, copy=False)

    adjacency = sp.coo_matrix(
        (values, (rows, columns)),
        shape=(n_users + n_items, n_users + n_items),
        dtype=np.float32,
    )
    adjacency.sum_duplicates()
    return adjacency.tocsr()


def symmetric_normalize(adjacency: sp.csr_matrix) -> sp.csr_matrix:
    """Return D^(-1/2) A D^(-1/2) with isolated-node rows left at zero."""
    degree = np.asarray(adjacency.sum(axis=1)).reshape(-1).astype(np.float64)
    inverse_sqrt = np.zeros_like(degree)
    nonzero = degree > 0
    inverse_sqrt[nonzero] = np.power(degree[nonzero], -0.5)
    diagonal = sp.diags(inverse_sqrt.astype(np.float32), format="csr")
    normalized = diagonal @ adjacency @ diagonal
    normalized = normalized.tocsr().astype(np.float32)
    normalized.eliminate_zeros()
    return normalized


def validate_graph(
    raw_adjacency: sp.csr_matrix,
    normalized: sp.csr_matrix,
    *,
    n_nodes: int,
) -> None:
    """Validate shape, symmetry, finiteness and non-negativity."""
    expected_shape = (n_nodes, n_nodes)
    if raw_adjacency.shape != expected_shape or normalized.shape != expected_shape:
        raise RuntimeError(
            f"Unexpected adjacency shape: raw={raw_adjacency.shape}, "
            f"normalized={normalized.shape}, expected={expected_shape}."
        )
    raw_difference = raw_adjacency - raw_adjacency.T
    norm_difference = normalized - normalized.T
    if raw_difference.nnz and np.max(np.abs(raw_difference.data)) > 1e-6:
        raise RuntimeError("Raw adjacency is not symmetric.")
    if norm_difference.nnz and np.max(np.abs(norm_difference.data)) > 1e-6:
        raise RuntimeError("Normalized adjacency is not symmetric.")
    if not np.isfinite(raw_adjacency.data).all():
        raise RuntimeError("Raw adjacency contains non-finite values.")
    if not np.isfinite(normalized.data).all():
        raise RuntimeError("Normalized adjacency contains non-finite values.")
    if (raw_adjacency.data < 0).any() or (normalized.data < 0).any():
        raise RuntimeError("Adjacency matrices contain negative values.")


def atomic_save_npz(matrix: sp.csr_matrix, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(output.name + ".tmp.npz")
    sp.save_npz(temporary, matrix, compressed=True)
    temporary.replace(output)


def atomic_write_dataframe(df: pd.DataFrame, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(output.name + ".tmp")
    df.to_csv(temporary, index=False)
    temporary.replace(output)


def atomic_write_json(payload: dict[str, Any], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(output.name + ".tmp")
    temporary.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    temporary.replace(output)


def build_graph_for_tau(
    train_df: pd.DataFrame,
    delta: np.ndarray,
    *,
    tau: float,
    n_users: int,
    n_items: int,
    output: Path,
) -> dict[str, Any]:
    weights = make_temporal_weights(delta, tau)
    users = train_df["userID"].to_numpy(dtype=np.int64)
    items = train_df["itemID"].to_numpy(dtype=np.int64)

    raw_adjacency = build_raw_bipartite_adjacency(
        users,
        items,
        weights,
        n_users=n_users,
        n_items=n_items,
    )
    normalized = symmetric_normalize(raw_adjacency)
    validate_graph(
        raw_adjacency,
        normalized,
        n_nodes=n_users + n_items,
    )
    atomic_save_npz(normalized, output)

    degree = np.asarray(raw_adjacency.sum(axis=1)).reshape(-1)
    unique_pairs = int(train_df[["userID", "itemID"]].drop_duplicates().shape[0])
    duplicate_interactions = int(len(train_df) - unique_pairs)
    return {
        "tau": float(tau),
        "path": str(output),
        "num_training_interactions": int(len(train_df)),
        "num_unique_user_item_pairs": unique_pairs,
        "num_duplicate_user_item_interactions": duplicate_interactions,
        "raw_adjacency_nnz": int(raw_adjacency.nnz),
        "normalized_adjacency_nnz": int(normalized.nnz),
        "weight_min": float(weights.min()),
        "weight_max": float(weights.max()),
        "weight_mean": float(weights.mean()),
        "weight_std": float(weights.std()),
        "zero_degree_nodes": int((degree == 0).sum()),
    }


def process_dataset(
    *,
    data_root: Path,
    dataset: str,
    input_suffix: str,
    output_dir_name: str,
    taus: Sequence[float],
    epsilon: float,
    separator: str,
    save_edge_values: bool,
    overwrite: bool,
) -> dict[str, Any]:
    """Build all requested tau graphs for one dataset."""
    dataset_dir = data_root / dataset
    interaction_path = dataset_dir / f"{dataset}{input_suffix}"
    output_dir = dataset_dir / output_dir_name

    all_interactions = read_temporal_inter(interaction_path, separator)
    n_users, n_items = validate_contiguous_ids(all_interactions, interaction_path)
    side_file_checks = validate_side_files(
        dataset_dir,
        n_users=n_users,
        n_items=n_items,
    )

    train_df = all_interactions.loc[all_interactions["x_label"] == 0].copy()
    if train_df.empty:
        raise ValueError(f"{interaction_path}: no training interactions found.")

    delta = compute_user_normalized_delta(train_df, epsilon=epsilon)
    tau_values = list(dict.fromkeys(float(tau) for tau in taus))
    if not tau_values:
        raise ValueError("At least one --taus value is required.")
    for tau in tau_values:
        safe_float_for_name(tau)

    graph_paths = [
        output_dir / f"ct_adj_user_tau{safe_float_for_name(tau)}.npz"
        for tau in tau_values
    ]
    stats_path = output_dir / "ct_adj_stats.csv"
    manifest_path = output_dir / "ct_adj_manifest.json"
    edge_path = output_dir / "ct_edge_values.csv"
    target_paths = graph_paths + [stats_path, manifest_path]
    if save_edge_values:
        target_paths.append(edge_path)

    existing = [path for path in target_paths if path.exists()]
    if existing and not overwrite:
        formatted = "\n".join(f"  - {path}" for path in existing)
        raise FileExistsError(
            "Output files already exist. Use --overwrite to regenerate:\n"
            + formatted
        )

    graph_stats: list[dict[str, Any]] = []
    for tau, graph_path in zip(tau_values, graph_paths, strict=True):
        stats = build_graph_for_tau(
            train_df,
            delta,
            tau=tau,
            n_users=n_users,
            n_items=n_items,
            output=graph_path,
        )
        stats["dataset"] = dataset
        graph_stats.append(stats)

    stats_df = pd.DataFrame(graph_stats)
    column_order = [
        "dataset",
        "tau",
        "path",
        "num_training_interactions",
        "num_unique_user_item_pairs",
        "num_duplicate_user_item_interactions",
        "raw_adjacency_nnz",
        "normalized_adjacency_nnz",
        "weight_min",
        "weight_max",
        "weight_mean",
        "weight_std",
        "zero_degree_nodes",
    ]
    atomic_write_dataframe(stats_df[column_order], stats_path)

    if save_edge_values:
        edge_values = train_df[["userID", "itemID", "timestamp"]].copy()
        edge_values["delta_user"] = delta
        for tau in tau_values:
            edge_values[f"weight_tau{safe_float_for_name(tau)}"] = (
                make_temporal_weights(delta, tau)
            )
        atomic_write_dataframe(edge_values, edge_path)

    train_timestamps = train_df["timestamp"].to_numpy(dtype=np.float64)
    user_spans = (
        train_df.groupby("userID", sort=False)["timestamp"].agg(lambda x: x.max() - x.min())
    )
    manifest = {
        "dataset": dataset,
        "interaction_file": str(interaction_path),
        "output_directory": str(output_dir),
        "graph_source": "training interactions only (x_label == 0)",
        "n_users": int(n_users),
        "n_items": int(n_items),
        "n_nodes": int(n_users + n_items),
        "num_all_interactions": int(len(all_interactions)),
        "num_train_interactions": int(len(train_df)),
        "num_valid_interactions": int((all_interactions["x_label"] == 1).sum()),
        "num_test_interactions": int((all_interactions["x_label"] == 2).sum()),
        "train_timestamp_min": float(train_timestamps.min()),
        "train_timestamp_max": float(train_timestamps.max()),
        "epsilon": float(epsilon),
        "zero_span_training_users": int((user_spans == 0).sum()),
        "delta_formula": (
            "(user_train_last_timestamp - interaction_timestamp) / "
            "max(user_train_last_timestamp - user_train_first_timestamp, epsilon)"
        ),
        "weight_formula": "exp(-delta_user / tau)",
        "normalization": "D^(-1/2) A D^(-1/2)",
        "duplicate_user_item_policy": (
            "sum temporal weights before symmetric normalization"
        ),
        "side_file_checks": side_file_checks,
        "graphs": graph_stats,
    }
    atomic_write_json(manifest, manifest_path)

    print("\n" + "=" * 72)
    print(f"Dataset             : {dataset}")
    print(f"Input               : {interaction_path}")
    print(f"Users / Items       : {n_users} / {n_items}")
    print(f"All / Train edges   : {len(all_interactions)} / {len(train_df)}")
    print(f"Zero-span users     : {(user_spans == 0).sum()}")
    print(f"Output directory    : {output_dir}")
    print(
        stats_df[
            [
                "tau",
                "num_unique_user_item_pairs",
                "normalized_adjacency_nnz",
                "weight_min",
                "weight_max",
                "weight_mean",
            ]
        ].to_string(index=False)
    )
    return manifest


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data_root",
        type=Path,
        default=Path("data"),
        help="Root directory containing one subdirectory per dataset.",
    )
    parser.add_argument(
        "--datasets",
        nargs="+",
        required=True,
        help="Dataset directory names, e.g. baby sports clothing microlens.",
    )
    parser.add_argument(
        "--input_suffix",
        default="_temporal.inter",
        help=(
            "Suffix appended to each dataset name "
            "(default: _temporal.inter)."
        ),
    )
    parser.add_argument(
        "--output_dir",
        default="continuous_time_adj",
        help="Output directory name inside each dataset directory.",
    )
    parser.add_argument(
        "--taus",
        type=float,
        nargs="+",
        required=True,
        help="One or more positive temporal kernel scales.",
    )
    parser.add_argument(
        "--epsilon",
        type=float,
        default=1e-12,
        help="Positive denominator floor for a user's training time span.",
    )
    parser.add_argument("--separator", default="\t")
    parser.add_argument(
        "--save_edge_values",
        action="store_true",
        help="Also save train-edge timestamps, deltas and weights as CSV.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite graph artifacts that already exist.",
    )
    return parser.parse_args(argv)


def main() -> None:
    args = parse_args()
    manifests = []
    for dataset in args.datasets:
        manifests.append(
            process_dataset(
                data_root=args.data_root,
                dataset=dataset,
                input_suffix=args.input_suffix,
                output_dir_name=args.output_dir,
                taus=args.taus,
                epsilon=args.epsilon,
                separator=args.separator,
                save_edge_values=args.save_edge_values,
                overwrite=args.overwrite,
            )
        )

    print(f"\n[DONE] Built continuous-time graphs for {len(manifests)} dataset(s).")


if __name__ == "__main__":
    main()
